/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package PRESENTACION;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import MODELO.Usuario;
import NEGOCIO.UsuarioDAO;
import NEGOCIO.IUsuarioDAO;
import javax.swing.JFrame;




public class Frm_Menu extends javax.swing.JFrame {

private Usuario usuario;
 

    public Frm_Menu() {
        initComponents();
     this.setLocationRelativeTo(null);
this.setExtendedState(JFrame.MAXIMIZED_BOTH);
  addMouseHoverEffect(panelpacientes);
        addMouseHoverEffect(panelmedicos);
        addMouseHoverEffect(panelconsultacita);
        addMouseHoverEffect(panelagendacitas);
        addMouseHoverEffect(panelsalir);

      
        
        } 
    
   
     
  public Frm_Menu(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
  configurarColorFondo();
        addMouseHoverEffect(panelpacientes);
        addMouseHoverEffect(panelmedicos);
        addMouseHoverEffect(panelconsultacita);
        addMouseHoverEffect(panelagendacitas);
        addMouseHoverEffect(panelsalir);

        mostrarDatosUsuario();
        configurarVisibilidadMenu();
        
     this.setLocationRelativeTo(null);
        
         addMouseHoverEffect(panelpacientes);
        addMouseHoverEffect(panelmedicos);
        addMouseHoverEffect(panelconsultacita);
        addMouseHoverEffect(panelagendacitas);
       
        
        addMouseHoverEffect(panelsalir);
        
        
      
        txtcliente.setText(usuario.getNombre());
       txttipo.setText(usuario.getTipoUsuario());
        
  txtcodusuario.setText(String.valueOf(usuario.getIdusuario()));
     
        if (usuario.getTipoUsuario().equalsIgnoreCase("Administrador")) {
          
        } else if (usuario.getTipoUsuario().equalsIgnoreCase("Paciente")) {

      
    
       panelmedicos.setVisible(false);
        
          panelconsultacita.setVisible(false);
            
            
     
         
         
        
 
         } else if (usuario.getTipoUsuario().equalsIgnoreCase("Médico")) {

     
      
     panelpacientes.setVisible(false);
         panelagendacitas.setVisible(false);

            
        
 

 } else if (usuario.getTipoUsuario().equalsIgnoreCase("Recepcionista")) {

       panelpacientes.setVisible(false);
         panelagendacitas.setVisible(false);
 
        
      }   
        
        
    }

    private void configurarColorFondo() {
        Color myColor = new Color(0, 153, 204);
        getContentPane().setBackground(myColor);
    }

    private void mostrarDatosUsuario() {
        txtcodusuario.setText(String.valueOf(usuario.getIdusuario()));
        txtcliente.setText(usuario.getNombre());
        txtemail.setText(usuario.getEmail());
        txttipo.setText(usuario.getTipoUsuario());
    }




    
   private void configurarVisibilidadMenu() {
        if (usuario.getTipoUsuario().equalsIgnoreCase("administrador")) {
            panelpacientes.setVisible(true);
            panelmedicos.setVisible(true);
            panelconsultacita.setVisible(true);
            panelagendacitas.setVisible(true);
            panelsalir.setVisible(true);
            
               Color myColor = new Color(0, 153, 204); 
        getContentPane().setBackground(myColor);
        
        } else if (usuario.getTipoUsuario().equalsIgnoreCase("cliente")) {
            
            
               Color myColor = new Color(255,255,255); 
        getContentPane().setBackground(myColor);
        
            panelpacientes.setVisible(false);
            panelmedicos.setVisible(false);
            panelconsultacita.setVisible(true);
            panelagendacitas.setVisible(true);
           panelsalir.setVisible(true);
           

        
    }
    
 
        
    }
    
    

private void ocultarTodosLosFormularios() {
    escritorio.removeAll();
    escritorio.repaint();
}
    

    private void addMouseHoverEffect(JPanel panel) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                panel.setBackground(Color.DARK_GRAY);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panel.setBackground(Color.BLACK); 
            }
        });
    }
    
    /**

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcodusuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txttipo = new javax.swing.JLabel();
        txtcliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtemail = new javax.swing.JLabel();
        txtcodcliente = new javax.swing.JLabel();
        panelpacientes = new javax.swing.JPanel();
        menueventos = new javax.swing.JLabel();
        panelmedicos = new javax.swing.JPanel();
        menuboleta = new javax.swing.JLabel();
        panelconsultacita = new javax.swing.JPanel();
        menuconsulta = new javax.swing.JLabel();
        panelusuario = new javax.swing.JPanel();
        menudestajero6 = new javax.swing.JLabel();
        panelagendacitas = new javax.swing.JPanel();
        menucompras = new javax.swing.JLabel();
        panelsalir = new javax.swing.JPanel();
        menusalir = new javax.swing.JLabel();
        labelusuario = new javax.swing.JLabel();
        labelcargo = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(0, 153, 204));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_______");

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISMEDIC");

        txtcodusuario.setBackground(new java.awt.Color(0, 153, 204));
        txtcodusuario.setForeground(new java.awt.Color(0, 153, 204));
        txtcodusuario.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(txtcodusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(988, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        txttipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txttipo.setForeground(new java.awt.Color(255, 255, 255));
        txttipo.setText("Tipo");

        txtcliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcliente.setForeground(new java.awt.Color(255, 255, 255));
        txtcliente.setText("Usuario");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        txtemail.setForeground(new java.awt.Color(102, 102, 102));
        txtemail.setText("jLabel2");

        txtcodcliente.setForeground(new java.awt.Color(102, 102, 102));
        txtcodcliente.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtemail)
                .addGap(45, 45, 45)
                .addComponent(txtcodcliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail)
                    .addComponent(txtcodcliente))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        panelpacientes.setBackground(new java.awt.Color(0, 0, 0));
        panelpacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelpacientesMouseClicked(evt);
            }
        });

        menueventos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menueventos.setForeground(new java.awt.Color(255, 255, 255));
        menueventos.setText("Pacientes");
        menueventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menueventosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelpacientesLayout = new javax.swing.GroupLayout(panelpacientes);
        panelpacientes.setLayout(panelpacientesLayout);
        panelpacientesLayout.setHorizontalGroup(
            panelpacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpacientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menueventos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelpacientesLayout.setVerticalGroup(
            panelpacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpacientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menueventos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelmedicos.setBackground(new java.awt.Color(0, 0, 0));
        panelmedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelmedicosMouseClicked(evt);
            }
        });

        menuboleta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuboleta.setForeground(new java.awt.Color(255, 255, 255));
        menuboleta.setText("Medicos");

        javax.swing.GroupLayout panelmedicosLayout = new javax.swing.GroupLayout(panelmedicos);
        panelmedicos.setLayout(panelmedicosLayout);
        panelmedicosLayout.setHorizontalGroup(
            panelmedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmedicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuboleta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelmedicosLayout.setVerticalGroup(
            panelmedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmedicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuboleta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelconsultacita.setBackground(new java.awt.Color(0, 0, 0));
        panelconsultacita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelconsultacitaMouseClicked(evt);
            }
        });

        menuconsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuconsulta.setForeground(new java.awt.Color(255, 255, 255));
        menuconsulta.setText("Ver Cita");

        javax.swing.GroupLayout panelconsultacitaLayout = new javax.swing.GroupLayout(panelconsultacita);
        panelconsultacita.setLayout(panelconsultacitaLayout);
        panelconsultacitaLayout.setHorizontalGroup(
            panelconsultacitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconsultacitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelconsultacitaLayout.setVerticalGroup(
            panelconsultacitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconsultacitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelusuario.setBackground(new java.awt.Color(0, 0, 0));
        panelusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelusuarioMouseClicked(evt);
            }
        });

        menudestajero6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelusuarioLayout = new javax.swing.GroupLayout(panelusuario);
        panelusuario.setLayout(panelusuarioLayout);
        panelusuarioLayout.setHorizontalGroup(
            panelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelusuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelusuarioLayout.setVerticalGroup(
            panelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelusuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelagendacitas.setBackground(new java.awt.Color(0, 0, 0));
        panelagendacitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelagendacitasMouseClicked(evt);
            }
        });

        menucompras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menucompras.setForeground(new java.awt.Color(255, 255, 255));
        menucompras.setText("Agenda Cita");

        javax.swing.GroupLayout panelagendacitasLayout = new javax.swing.GroupLayout(panelagendacitas);
        panelagendacitas.setLayout(panelagendacitasLayout);
        panelagendacitasLayout.setHorizontalGroup(
            panelagendacitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelagendacitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menucompras, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelagendacitasLayout.setVerticalGroup(
            panelagendacitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelagendacitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menucompras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelsalir.setBackground(new java.awt.Color(0, 0, 0));
        panelsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelsalirMouseClicked(evt);
            }
        });

        menusalir.setBackground(new java.awt.Color(0, 0, 0));
        menusalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menusalir.setForeground(new java.awt.Color(255, 255, 255));
        menusalir.setText("Salir");

        javax.swing.GroupLayout panelsalirLayout = new javax.swing.GroupLayout(panelsalir);
        panelsalir.setLayout(panelsalirLayout);
        panelsalirLayout.setHorizontalGroup(
            panelsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menusalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelsalirLayout.setVerticalGroup(
            panelsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menusalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        labelusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelusuario.setForeground(new java.awt.Color(255, 255, 255));

        labelcargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcargo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelcargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(panelpacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelmedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelconsultacita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelagendacitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcliente)
                    .addComponent(labelusuario))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttipo)
                    .addComponent(labelcargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelmedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelconsultacita, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelagendacitas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(panelusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Sistema de centro médico");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelpacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpacientesMouseClicked


  ocultarTodosLosFormularios();
        FrmPaciente ventana = new     FrmPaciente  ();
escritorio.add(ventana);

ventana.show();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_panelpacientesMouseClicked

    private void panelsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsalirMouseClicked

  this.dispose();
         FrmLogin  frm = new  FrmLogin ();
        frm.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_panelsalirMouseClicked

    private void panelconsultacitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelconsultacitaMouseClicked

        
        

  ocultarTodosLosFormularios();
      FrmListado_Citas  ventana = new FrmListado_Citas ();
escritorio.add(ventana);

ventana.show();


        // TODO add your handling code here:
    }//GEN-LAST:event_panelconsultacitaMouseClicked

    private void panelmedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelmedicosMouseClicked
  ocultarTodosLosFormularios();
        FrmMedico ventana = new     FrmMedico  ();
escritorio.add(ventana);

ventana.show();


        // TODO add your handling code here:
    }//GEN-LAST:event_panelmedicosMouseClicked

    private void panelagendacitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelagendacitasMouseClicked


      
  ocultarTodosLosFormularios();
        FrmAgenda_Cita ventana = new           FrmAgenda_Cita  ();
escritorio.add(ventana);

ventana.show();




        // TODO add your handling code here:
    }//GEN-LAST:event_panelagendacitasMouseClicked

    private void panelusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelusuarioMouseClicked




        // TODO add your handling code here:
    }//GEN-LAST:event_panelusuarioMouseClicked

    private void menueventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueventosMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_menueventosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel labelcargo;
    public static javax.swing.JLabel labelusuario;
    private javax.swing.JLabel menuboleta;
    private javax.swing.JLabel menucompras;
    private javax.swing.JLabel menuconsulta;
    private javax.swing.JLabel menudestajero6;
    private javax.swing.JLabel menueventos;
    private javax.swing.JLabel menusalir;
    private javax.swing.JPanel panelagendacitas;
    private javax.swing.JPanel panelconsultacita;
    private javax.swing.JPanel panelmedicos;
    private javax.swing.JPanel panelpacientes;
    private javax.swing.JPanel panelsalir;
    private javax.swing.JPanel panelusuario;
    private javax.swing.JLabel txtcliente;
    public static javax.swing.JLabel txtcodcliente;
    public static javax.swing.JLabel txtcodusuario;
    public static javax.swing.JLabel txtemail;
    private javax.swing.JLabel txttipo;
    // End of variables declaration//GEN-END:variables

}
