/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRESENTACION;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import MODELO.Cita;
import MODELO.Especialidad;
import MODELO.Paciente;
import NEGOCIO.EspecialidadDAO;

import NEGOCIO.CitaDAO;
import NEGOCIO.PacienteDAO;
import NEGOCIO.CitaDAO;

//********************************************
import UTILITARIOS.ColorDetalle;
import javax.swing.table.TableColumnModel;
import UTILITARIOS.Centrar_Datos_Celda_Jtable;
import javax.swing.DefaultComboBoxModel;
import javax.swing.RowFilter;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
//********************************************


public class FrmAgenda_Cita extends javax.swing.JInternalFrame {

        private DefaultTableModel modeloTabla;

   
      public FrmAgenda_Cita() {
        initComponents();
           EspecialidadDAO dao = new EspecialidadDAO();
    DefaultComboBoxModel modelo = new DefaultComboBoxModel(dao.mostrarEspecialidades());
    cboespecialidad.setModel(modelo);

 
 DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String fechaActual = LocalDate.now().format(formatoFecha);

    
    DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");
    String horaActual = LocalTime.now().format(formatoHora);


    txtfecha.setText(fechaActual);
    txthora.setText(horaActual);

             
             
         getContentPane().setBackground(Color.WHITE);
 
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null); 

        
     
        this.setClosable(false);
     
       
        this.setBorder(null);
        
     
           
        
     //********************************************   
 
    
    

        
    //********************************************
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnborrar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmotivo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboespecialidad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtcodigopaciente = new javax.swing.JLabel();
        txtcodigomedico = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnguardar.setBackground(new java.awt.Color(204, 204, 0));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Registrar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtnombres.setEditable(false);

        txtapellidos.setEditable(false);

        jLabel2.setText("Nombres");

        btnborrar.setBackground(new java.awt.Color(255, 153, 51));
        btnborrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnborrar.setForeground(new java.awt.Color(255, 255, 255));
        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btncerrar.setBackground(new java.awt.Color(0, 0, 204));
        btncerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellidos");

        jLabel5.setText("DNI");

        txtmotivo.setEditable(false);

        jLabel6.setText("Motivo de Consulta");

        jLabel7.setText("Fecha");

        jLabel8.setText("Hora");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paciente.jpg"))); // NOI18N

        jLabel9.setText("Especialidad Motivo de Consulta");

        cboespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboespecialidadActionPerformed(evt);
            }
        });

        jLabel10.setText("Estado");

        txtestado.setEditable(false);
        txtestado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtestado.setForeground(new java.awt.Color(255, 204, 0));
        txtestado.setText("PENDIENTE");
        txtestado.setToolTipText("");

        btnbuscar.setBackground(new java.awt.Color(0, 204, 0));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setText("Busar  Por DNI");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtcodigopaciente.setForeground(new java.awt.Color(255, 255, 255));
        txtcodigopaciente.setText("0");

        txtcodigomedico.setForeground(new java.awt.Color(255, 255, 255));
        txtcodigomedico.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(113, 113, 113)
                            .addComponent(txtcodigomedico))
                        .addComponent(txtapellidos)
                        .addComponent(txtdni)
                        .addComponent(txtfecha)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(88, 88, 88)
                            .addComponent(txtcodigopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)
                        .addComponent(txthora)
                        .addComponent(cboespecialidad, 0, 330, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtnombres)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtestado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcodigopaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcodigomedico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtestado, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
limpiar();
     
           
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

      
         try {
      String fecha = txtfecha.getText().trim();
        String hora = txthora.getText().trim();
           String dni = txtdni.getText().trim();
      int codigopaciente =  Integer.parseInt(txtcodigopaciente.getText());
      
         int codigomedico=  Integer.parseInt(txtcodigomedico.getText());
   
        String estado = txtestado.getText().trim();

  
        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe consultar al  paciente por DNI.", "Falta nombre", JOptionPane.WARNING_MESSAGE);
            txtdni.requestFocus();
            return;
        }

       

      

        CitaDAO dao = new CitaDAO();
      

       

        if (fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la fecha.", "Falta fecha", JOptionPane.WARNING_MESSAGE);
            txtfecha.requestFocus();
            return;
        }

      


if (fecha.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Ingrese la fecha.", "Falta fecha", JOptionPane.WARNING_MESSAGE);
    txtfecha.requestFocus();
    return;
}


if (!fecha.matches("\\d{4}-\\d{2}-\\d{2}")) {
    JOptionPane.showMessageDialog(this, "Ingrese la fecha en formato correcto (AAAA-MM-DD).", "Formato incorrecto", JOptionPane.WARNING_MESSAGE);
    txtfecha.requestFocus();
    return;
}
        if (hora.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la hora.", "Falta motivo", JOptionPane.WARNING_MESSAGE);
            txthora.requestFocus();
            return;
        }

 


if (!hora.matches("([01]\\d|2[0-3]):[0-5]\\d")) {
    JOptionPane.showMessageDialog(this, "Ingrese la hora en formato correcto (HH:mm).", "Formato incorrecto", JOptionPane.WARNING_MESSAGE);
    txthora.requestFocus();
    return;
}

       Cita nuevo = new Cita();
        nuevo.setFecha(fecha);
        nuevo.setHora(hora);
        
        nuevo.setCodigopaciente(codigopaciente);
        
        
         Especialidad esp = (Especialidad) cboespecialidad.getSelectedItem();
        int idespecialidad = esp.getIdespecialidad();

          nuevo.setIdespecialidad(idespecialidad); 

          nuevo.setCodigomedico(codigomedico);
          
        nuevo.setMotivo(estado);

        dao.registrar(nuevo);

        JOptionPane.showMessageDialog(this, "Agenda Cita registrado exitosamente.", "Registro correcto", JOptionPane.INFORMATION_MESSAGE);
        limpiar();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al registrar agenda cita: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

        
        
        
        
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        
         String dni = txtdni.getText().trim();

    if (dni.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el DNI del paciente.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        txtdni.requestFocus();
        return;
    }

    CitaDAO dao = new CitaDAO(); 
    Paciente paciente = dao.buscarPacientePorDni(dni);

    if (paciente != null) {
        txtcodigopaciente.setText(String.valueOf(paciente.getCodigopaciente()));
        txtnombres.setText(paciente.getNombres());
        txtapellidos.setText(paciente.getApellidos());
        txtmotivo.setText(paciente.getMotivo());
    
    } else {
        JOptionPane.showMessageDialog(this, "Paciente no encontrado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        limpiar();
    }

        
        
        
        
        
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void cboespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboespecialidadActionPerformed
        Especialidad esp = (Especialidad) cboespecialidad.getSelectedItem();
    
    if (esp != null) {
        txtcodigomedico.setText(String.valueOf(esp.getIdespecialidad())); 
    }
    }//GEN-LAST:event_cboespecialidadActionPerformed







    private void limpiar() {
         txtdni.setText("");
    txtnombres.setText("");
    
    txtfecha.setText("");
    txthora.setText("");
    txtestado.setText("");
    txtcodigopaciente.setText("");
    txtcodigomedico.setText("");
    txtestado.setText("");
    txtmotivo.setText("");

    }
    




   

 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cboespecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JLabel txtcodigomedico;
    private javax.swing.JLabel txtcodigopaciente;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtmotivo;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
