/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRESENTACION;

import MODELO.Cita;
import NEGOCIO.CitaDAO;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import javax.swing.table.DefaultTableModel;


//********************************************

import javax.swing.table.TableColumnModel;
import UTILITARIOS.Centrar_Datos_Celda_Jtable;
import javax.swing.table.JTableHeader;

import UTILITARIOS.ColorDetalleEstadoJTable;
import java.util.List;

//********************************************


public class FrmListado_Citas extends javax.swing.JInternalFrame {

  
   
      public FrmListado_Citas() {
        initComponents();
        
            personalizarFormulario();
        mostrarListadoCitas();
       

              
       
     
             } 
      
      
      
      
 private void personalizarFormulario() {
        getContentPane().setBackground(Color.WHITE);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        this.setClosable(false);
        this.setBorder(null);

       

        JTableHeader header = listado.getTableHeader();
header.setFont(new Font("Segoe UI", Font.BOLD, 14));
header.setBackground(new Color(30, 136, 229)); // Azul elegante
header.setForeground(Color.WHITE);

        TableColumnModel columnModel = listado.getColumnModel();
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            columnModel.getColumn(i).setCellRenderer(new Centrar_Datos_Celda_Jtable());
        }
    }

    private void mostrarListadoCitas() {
        CitaDAO dao = new CitaDAO();
        DefaultTableModel modelo = dao.mostrarCitas();
        listado.setModel(modelo);
        listado.setDefaultRenderer(Object.class, new ColorDetalleEstadoJTable());
    }

    private void filtrarListadoCitas(String texto) {
        CitaDAO dao = new CitaDAO();
        DefaultTableModel modelo = dao.mostrarCitas();
        DefaultTableModel filtrado = new DefaultTableModel(
            new Object[]{"Código", "Fecha", "Hora", "Paciente", "Especialidad", "Médico", "Estado"}, 0
        );

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String paciente = modelo.getValueAt(i, 3).toString().toLowerCase();
            if (paciente.contains(texto.toLowerCase())) {
                filtrado.addRow(new Object[]{
                    modelo.getValueAt(i, 0),
                    modelo.getValueAt(i, 1),
                    modelo.getValueAt(i, 2),
                    modelo.getValueAt(i, 3),
                    modelo.getValueAt(i, 4),
                    modelo.getValueAt(i, 5),
                    modelo.getValueAt(i, 6)
                });
            }
        }

        listado.setModel(filtrado);
        listado.setDefaultRenderer(Object.class, new ColorDetalleEstadoJTable());
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ));
        listado.setFocusable(false);
        listado.setSelectionBackground(new java.awt.Color(0, 204, 204));
        listado.getTableHeader().setReorderingAllowed(false);
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Seleccione una cita para marcarla como Atendida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents






private void seleccionarFilaYActualizarEstado() {
    int filaSeleccionada = listado.getSelectedRow();

    if (filaSeleccionada != -1) {
        int codigocita = Integer.parseInt(listado.getValueAt(filaSeleccionada, 0).toString());
        String estadoActual = listado.getValueAt(filaSeleccionada, 6).toString();

        if (!estadoActual.equalsIgnoreCase("ATENDIDO")) {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas marcar esta cita como ATENDIDO?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                CitaDAO dao = new CitaDAO();
                dao.actualizarEstadoCita(codigocita, "ATENDIDO");
                mostrarListadoCitas(); 
            }
        } else {
            JOptionPane.showMessageDialog(this, "Esta cita ya está marcada como ATENDIDO.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona una fila para cambiar su estado.");
    }
}

 
    
    
    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked


 if (evt.getClickCount() == 1) { 
            seleccionarFilaYActualizarEstado();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado;
    // End of variables declaration//GEN-END:variables
}
